---
title: "p8105_hw2_yx2710"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
```

Problem 1 - nyc  transit data

```{r}
nyc_transit_df = read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")%>%
  janitor::clean_names()%>%
  select(line, station_name, station_latitude, station_longitude, starts_with("routes"), entry, vending, entrance_type, ada)%>%
  mutate(entry = as.logical(ifelse(entry == "YES", "TRUE", "FALSE")))
```
The variables that nyc transit dataset contains are `r names(nyc_transit_df)` and it has `r ncol(nyc_transit_df)` columns and `r nrow(nyc_transit_df)` rows.

How many distinct stations are there?
```{r}
station = distinct(nyc_transit_df, station_name, line, .keep_all = TRUE)
nrow(station)
```
There are `r nrow(station)` distinct stations.



Problem2 - trash
Mr. Trash Wheel sheet:
```{r}
mr_trash_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Mr. Trash Wheel")%>%
  janitor::clean_names()%>%
  select(dumpster:homes_powered) %>%
  drop_na(dumpster)%>%
  filter(dumpster != "Grand Total")%>%
  mutate(sports_balls = as.integer(round(sports_balls)))

```

Professor Trash Wheel:
```{r}
prof_trash_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Professor Trash Wheel")%>%
  janitor::clean_names()%>%
  select(dumpster:homes_powered) %>%
  drop_na(dumpster)%>%
  mutate(sports_balls = as.integer(round(sports_balls)))
```

Combine two dataset
```{r}
mr_trash_bind_df = mr_trash_df %>%
  mutate(cleaner = "Mr. Trash") %>%
  mutate(dumpster = as.numeric(dumpster))

prof_trash_bind_df = mutate(prof_trash_df, cleaner = "Professor Trash")
class(prof_trash_bind_df$dumpster)

trash_combine_df = 
  bind_rows(mr_trash_bind_df, prof_trash_bind_df)
```



