p8105_hw2_yx2710
================

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.1      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

Problem 1 - nyc transit data

``` r
nyc_transit_df = read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")%>%
  janitor::clean_names()%>%
  select(line, station_name, station_latitude, station_longitude, starts_with("route"), entry, vending, entrance_type, ada)%>%
  mutate(entry = as.logical(ifelse(entry == "YES", "TRUE", "FALSE")))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The variables that nyc transit dataset contains are line, station_name,
station_latitude, station_longitude, route1, route2, route3, route4,
route5, route6, route7, route8, route9, route10, route11, entry,
vending, entrance_type, ada and it has 19 columns and 1868 rows.

Q:How many distinct stations are there?

``` r
station = distinct(nyc_transit_df, station_name, line, .keep_all = TRUE)
nrow(station)
```

    ## [1] 465

A:There are 465 distinct stations.

Q:How many stations are ADA compliant?

``` r
station_ada = filter(nyc_transit_df, ada == "TRUE")
nrow(station_ada)
```

    ## [1] 468

A: There are 468 stations that are ADA compliant.

Q:What proportion of station entrances / exits without vending allow
entrance?

``` r
proportion_e_nov = nrow(filter(nyc_transit_df, entry == "TRUE", vending == "NO"))/nrow(filter(nyc_transit_df, vending == "NO"))
```

A: The proportion of station entrances / exits without vending allow
entrance is 0.3770492.

Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train? Of the stations
that serve the A train, how many are ADA compliant?

``` r
nyc_transit_re_df = 
  nyc_transit_df%>%
  mutate(
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11))%>%
  pivot_longer(route1:route11, 
               names_to = "route",
               values_to = "route_number")

station_re = distinct(nyc_transit_re_df, station_name, line, .keep_all = TRUE)

station_A = filter(station_re, route_number == "A" )
nrow(station_A)
```

    ## [1] 60

``` r
station_A_ada = filter(station_A, ada == "TRUE")
nrow(station_A_ada)
```

    ## [1] 17

There are 60 distinct stations serve the A train. Of the stations that
serve the A train, 17 are ADA compliant.

Problem2 - trash Mr. Trash Wheel sheet:

``` r
mr_trash_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Mr. Trash Wheel")%>%
  janitor::clean_names()%>%
  select(dumpster:homes_powered) %>%
  drop_na(dumpster)%>%
  filter(dumpster != "Grand Total")%>%
  mutate(sports_balls = as.integer(round(sports_balls)))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`
    ## • `` -> `...17`

Professor Trash Wheel:

``` r
prof_trash_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Professor Trash Wheel")%>%
  janitor::clean_names()%>%
  select(dumpster:homes_powered) %>%
  drop_na(dumpster)%>%
  mutate(sports_balls = as.integer(round(sports_balls)))
```

Combine two dataset

``` r
mr_trash_bind_df = mr_trash_df %>%
  mutate(cleaner = "Mr. Trash") %>%
  mutate(dumpster = as.numeric(dumpster))

prof_trash_bind_df = mutate(prof_trash_df, cleaner = "Professor Trash")
class(prof_trash_bind_df$dumpster)
```

    ## [1] "numeric"

``` r
trash_combine_df = 
  bind_rows(mr_trash_bind_df, prof_trash_bind_df)
```

Problem3 - fivethirtyeight

``` r
pols_month_df = 
  read_csv("./data/fivethirtyeight_datasets/pols-month.csv")%>%
  janitor::clean_names()%>%
  separate(col = mon, into = c("year", "month", "day"), sep = "-")%>%
  mutate(month = as.numeric(month), 
         month = month.abb[month],
         president = ifelse(prez_gop == 0, "dem", "gop"))%>%
  select(-prez_dem, -prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
